# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
                ('url', models.URLField(blank=True)),
                ('imagen', models.ImageField(blank=True, upload_to='productos/archivos/%Y/%m/%d')),
            ],
            options={
                'ordering': ('producto',),
                'db_table': 'archivoprod',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='ImagenesProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
                ('url', models.URLField(blank=True)),
                ('imagen', models.ImageField(blank=True, upload_to='productos/imagenes/%Y/%m/%d')),
            ],
            options={
                'ordering': ('producto',),
                'db_table': 'imagenprod',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ManyToManyField(related_name='productos', to='shop.Categoria')),
            ],
            options={
                'ordering': ('nombre',),
                'db_table': 'producto',
            },
        ),
        migrations.AddField(
            model_name='imagenesproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgprod', to='shop.Producto'),
        ),
        migrations.AddField(
            model_name='archivosproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archprod', to='shop.Producto'),
        ),
        migrations.AlterIndexTogether(
            name='producto',
            index_together=set([('id', 'slug')]),
        ),
    ]
