# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181019_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigociber',
            field=models.CharField(default='', max_length=30),
        ),
    ]
