# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_producto_codigociber'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenesproducto',
            name='principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigociber',
            field=models.CharField(default='', max_length=30, verbose_name='Codigo CiberService'),
        ),
    ]
