# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_imagenportada_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='etiquetas',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
