# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cp',
            field=models.CharField(default='', max_length=10, verbose_name='Codigo Postal'),
        ),
        migrations.AddField(
            model_name='orden',
            name='domicilio',
            field=models.CharField(default='', max_length=80),
        ),
    ]
